package test.wssecfvt.derivekey;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-02-01T15:32:53.062-06:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://derivekey.wssecfvt.test", name = "DeriveKeyPortType")
@XmlSeeAlso({test.wssecfvt.derivekey.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DeriveKeyPortType {

    @WebResult(name = "getVerResponse", targetNamespace = "http://derivekey.wssecfvt.test/types", partName = "out")
    @WebMethod
    public test.wssecfvt.derivekey.types.GetVerResponse invoke(
        @WebParam(partName = "in", name = "getVer", targetNamespace = "http://derivekey.wssecfvt.test/types")
        test.wssecfvt.derivekey.types.GetVer in
    );
}
