# Documentation in https://dependabot.com/docs/config-file/
# Can validate at  https://dependabot.com/docs/config-file/validator/
version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/dev/cnf/dependabot/check_this_in_if_it_changes/"
    update_schedule: "daily"
    default_assignees:
      - "tevans78"
      - "cbridgha"
    target_branch: "integration"
