package fats.cxf.mustunderstand;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-01-15T23:06:09.236-06:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://mustunderstand.cxf.fats", name = "MustUnderstand")
@XmlSeeAlso({fats.cxf.mustunderstand.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MustUnderstand {

    @WebResult(name = "getVerResponse", targetNamespace = "http://mustunderstand.cxf.fats/types", partName = "out")
    @WebMethod
    public fats.cxf.mustunderstand.types.GetVerResponse invoke(
        @WebParam(partName = "in", name = "getVer", targetNamespace = "http://mustunderstand.cxf.fats/types")
        fats.cxf.mustunderstand.types.GetVer in
    );
}
